development:
  adapter: postgresql
  encoding: unicode
  database: lojawebdb
  pool: 5
  username: casa
  password: 123456

  port: 5432
  host: 127.0.0.1
  
test:
  adapter: postgresql
  encoding: unicode
  database: lojawebdb
  pool: 5
  username: casa
  password: 123456

production:
  adapter: postgresql
  encoding: unicode
  database: lojawebdb
  pool: 5
  username: casa
  password: 123456
